stages:
  - build
  - deploy

.build:
  stage: build
  image: docker:20.10.16
  services:
    - name: docker:dind
      alias: thedockerhost
  variables:
    DOCKER_HOST: tcp://thedockerhost:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ''
  before_script:
    - echo "$DOCKER_REGISTRY_PASS" | docker login $DOCKER_REGISTRY --username $DOCKER_REGISTRY_USER --password-stdin
  script:
    - cp $ENV .env.production
    - docker build -t $IMAGE .
    - docker push $IMAGE

# Job build-dev cho nhánh dev
build:
  extends: .build
  only:
    refs:
      - master

.deploy:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY root@$SERVER "
      echo "$DOCKER_REGISTRY_PASS" | docker login $DOCKER_REGISTRY --username $DOCKER_REGISTRY_USER --password-stdin &&
      docker stop $CONTAINER || true &&
      docker rm $CONTAINER || true &&
      docker image rm $IMAGE || true &&
      docker pull $IMAGE &&
      docker run -d --name $CONTAINER --restart=always --network internal_network $IMAGE"

# Job deploy cho nhánh main
deploy:
  extends: .deploy
  only:
    refs:
      - master
